### ISSUE TITLE
About The TLESS result

### ISSUE THREAD

**Issue by qifengluo** [fylwen/DISP-6D#2]
Hi, I found that the data for AAE and Multipath AAE [38] in the text is different from the original text. What is the reason for this?

**Comment by fylwen** [comment]
Hello. Thank you for your question.

The original Multipath-AAE reports by rendering with the _reconstructed_ T-LESS objects (cf. Multipath-AAE Fig.1, Sec 4.2, and also the demo shown in their github-repo). But in DISP6D, we report and compare with related methods by rendering with the _CAD_ ones (cf. DISP6D, Sec 5.4-Baselines).

The reconstructed objects often suffer from inaccurate geometry, hindering the bounding box comparison for translation estimation (cf. AAE-IJCV, Sec 4.4), resulting in a worse recall rate under e_vsd.

**Comment by qifengluo** [comment]
Thanks for your reply！！！
